#ifndef __constants_h_included__
#define __constants_h_included__

enum {
    MEMTYPE_RESERVED = 0,
    MEMTYPE_FPM,
    MEMTYPE_EDO,
    MEMTYPE_PNR,
    MEMTYPE_SDR,
    MEMTYPE_ROM,
    MEMTYPE_DDRSGR,
    MEMTYPE_DDR,
    MEMTYPE_DDR2,
    MEMTYPE_DDR2_FB,
    MEMTYPE_DDR2_FB_PROBE,
    MEMTYPE_DDR3,
    MEMTYPE_DDR4
};

enum {
    DDR2MODULETYPE_UNDEFINED    = 0x00,
    DDR2MODULETYPE_RDIMM        = 0x01,
    DDR2MODULETYPE_UDIMM        = 0x02,
    DDR2MODULETYPE_SO_DIMM      = 0x04,
    DDR2MODULETYPE_72B_SO_CDIMM = 0x06,
    DDR2MODULETYPE_72B_SO_RDIMM = 0x07,
    DDR2MODULETYPE_MICRO_DIMM   = 0x08,
    DDR2MODULETYPE_MINI_RDIMM   = 0x10,
    DDR2MODULETYPE_MINI_UDIMM   = 0x20,
};

enum {
    DDR3MODULETYPE_UNDEFINED    = 0x00,
    DDR3MODULETYPE_RDIMM,
    DDR3MODULETYPE_UDIMM,
    DDR3MODULETYPE_SO_DIMM,
    DDR3MODULETYPE_MICRO_DIMM,
    DDR3MODULETYPE_MINI_RDIMM,
    DDR3MODULETYPE_MINI_UDIMM,
    DDR3MODULETYPE_MINI_CDIMM,
    DDR3MODULETYPE_72B_SO_UDIMM,
    DDR3MODULETYPE_72B_SO_RDIMM,
    DDR3MODULETYPE_72B_SO_CDIMM,
    DDR3MODULETYPE_LRDIMM,
    DDR3MODULETYPE_16B_SO_DIMM,
    DDR3MODULETYPE_32B_SO_DIMM
};

enum {
    CONFIG_DATA_PARITY = 1,
    CONFIG_DATA_ECC = 2,
    CONFIG_ADDR_PARITY = 4
};

enum {
    ATTR_DDR_BUFFERED = 1,
    ATTR_DDR_REGISTERED = 2,
};

#define MAX_RANKS       8

#endif
