#ifndef __constants_h_include__
#define __constants_h_include__

enum {
  MEMTYPE_RESERVED   = 0,
  MEMTYPE_FPM,
  MEMTYPE_EDO,
  MEMTYPE_PNR,
  MEMTYPE_SDR,
  MEMTYPE_ROM,
  MEMTYPE_DDRSGR,
  MEMTYPE_DDRSDR,
  MEMTYPE_DDR2SDR,
  MEMTYPE_DDR2_FB,
  MEMTYPE_DDR2_FB_PROBE,
  MEMTYPE_DDR3SDR
};

enum {
  DDR3MODULETYPE_UNDEFINED = 0,
  DDR3MODULETYPE_RDIMM,
  DDR3MODULETYPE_UDIMM,
  DDR3MODULETYPE_SO_DIMM,
  DDR3MODULETYPE_MICRO_DIMM,
  DDR3MODULETYPE_MINI_RDIMM,
  DDR3MODULETYPE_MINI_UDIMM
};

enum {
  CONFIG_DATA_PARITY = 1,
  CONFIG_DATA_ECC    = 2,
  CONFIG_ADDR_PARITY = 4
};

enum {
  ATTR_DDR_BUFFERED    = 1,
  ATTR_DDR_REGISTERED  = 2,

  ATTR_DDR2_REGISTERED = 1
};

#define MAX_RANKS       8

#endif
